ktor:
  application:
    modules:
      - com.where.to.go.ApplicationKt.module

  deployment:
    port: 8080

  database:
    url: "jdbc:postgresql://localhost:5432/db_v1"
    driver: "org.postgresql.Driver"
    user: "timofey"
    password: "password"

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
